name: waifu
description: Waifu onboarding application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dio: ^4.0.1
  json_annotation: 4.5.0
  retrofit: ">=3.0.0 <4.0.0"

  cached_network_image: ^3.2.1

  masonry_grid: ^1.0.0

  elementary: 1.3.1
  flutter_svg: 1.1.0
  get_it: ^7.2.0
  intl: ^0.17.0
  google_fonts: ^3.0.1
  flutter_sticky_header: ^0.6.3
  golden_toolkit: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

  flutter_lints: ^2.0.0

  build_runner: 2.1.11
  json_serializable: 6.2.0
  retrofit_generator: 4.0.1

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
