name: waifu
description: Waifu onboarding application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dio: ^4.0.1
  json_annotation: ^4.1.0

  elementary: ^0.1.3
  flutter_svg: ^0.23.0+1
  get_it: ^7.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  dart_code_metrics: ^4.6.0
  flutter_lints: ^1.0.0
  json_serializable: ^5.0.0
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true
